/**
 * Generate TypeScript types from api.yaml using openapi-typescript.
 *
 * Produces:
 *   src/generated/openapi-types.d.ts  — raw openapi-typescript output
 *   src/generated/models/index.ts     — re-export layer preserving the public API
 *
 * String enum schemas get a const object + type alias (same pattern the old
 * Java-based generator produced). Object schemas get a simple type alias that
 * points into the openapi-types namespace.
 */

import { readFileSync, mkdirSync, writeFileSync } from 'node:fs';
import { URL } from 'node:url';
import openapiTS, { astToString } from 'openapi-typescript';
import YAML from 'yaml';

// ── 1. Generate the raw .d.ts ────────────────────────────────────────────────

const specUrl = new URL('../api.yaml', import.meta.url);
const ast = await openapiTS(specUrl);
const dts = astToString(ast);

mkdirSync(new URL('../src/generated/models', import.meta.url), { recursive: true });
writeFileSync(new URL('../src/generated/openapi-types.d.ts', import.meta.url), dts);
console.log('  wrote src/generated/openapi-types.d.ts');

// ── 2. Parse api.yaml to discover schema metadata ───────────────────────────

const spec = YAML.parse(readFileSync(specUrl, 'utf-8'));
const schemas = spec.components?.schemas ?? {};

// Schemas whose `type` is `string` with an `enum` array get const-object
// treatment.
const enumSchemas = new Map();
const objectSchemas = [];

for (const [name, schema] of Object.entries(schemas)) {
  if (schema.type === 'string' && Array.isArray(schema.enum)) {
    enumSchemas.set(name, schema.enum);
  } else {
    objectSchemas.push(name);
  }
}

// ── 3. Generate the re-export layer ──────────────────────────────────────────

const lines = [
  '/**',
  ' * Re-export layer — preserves the public API surface.',
  ' *',
  ' * AUTO-GENERATED by scripts/generate-models.js — do not edit by hand.',
  ' */',
  '',
  "import type { components } from '../openapi-types.js';",
  '',
  '// ── Object schemas ────────────────────────────────────────────────────────',
  '',
];

for (const name of objectSchemas) {
  lines.push(`export type ${name} = components['schemas']['${name}'];`);
}

lines.push('');
lines.push('// ── Enum schemas (const object + type alias) ────────────────────────────');
lines.push('');

for (const [name, values] of enumSchemas) {
  const entries = values.map((v) => `  ${v}: '${v}'`).join(',\n');
  lines.push(`export const ${name} = {`);
  lines.push(entries);
  lines.push('} as const;');
  lines.push(`export type ${name} = typeof ${name}[keyof typeof ${name}];`);
  lines.push('');
}

writeFileSync(
  new URL('../src/generated/models/index.ts', import.meta.url),
  lines.join('\n'),
);
console.log('  wrote src/generated/models/index.ts');
